import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import UpperFooter from '../components/UpperFooter'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>
        <HeroSection/>
        <UpperFooter/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
